import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * FACE GmbH product stack — devices commonly specified/installed by FACE
 * (Professional Audio, Video-/Lichttechnik, Gebäudeautomation).
 *
 * Port counts/specs are representative starting points; verify against the
 * concrete model variant before relying on a schematic for procurement.
 */
export const templates: DeviceTemplate[] = [
  // ── Bose Professional — ControlSpace DSP ─────────────────────────
  {
    id: "c0a80101-0fac-4000-8000-000000000f01",
    deviceType: "audio-dsp",
    label: "Bose ControlSpace EX-1280C",
    manufacturer: "Bose Professional",
    modelNumber: "ControlSpace EX-1280C",
    referenceUrl: "https://pro.bose.com/en_us/products/signal_processing/controlspace_ex.html",
    searchTerms: ["bose", "controlspace", "ex-1280c", "dsp", "conferencing", "dante", "amplink"],
    powerDrawW: 60,
    heightMm: 44,
    widthMm: 483,
    depthMm: 305,
    weightKg: 4.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Dante", "dante", "bidirectional"),
      port("AmpLink", "dante", "output", "rj45"),
      port("USB (Audio/Control)", "usb", "bidirectional"),
      port("Network", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0fac-4000-8000-000000000f02",
    deviceType: "audio-dsp",
    label: "Bose ControlSpace EX-440C",
    manufacturer: "Bose Professional",
    modelNumber: "ControlSpace EX-440C",
    referenceUrl: "https://pro.bose.com/en_us/products/signal_processing/controlspace_ex.html",
    searchTerms: ["bose", "controlspace", "ex-440c", "dsp", "conferencing", "aec"],
    powerDrawW: 45,
    heightMm: 44,
    widthMm: 483,
    depthMm: 305,
    weightKg: 4.0,
    ports: [
      ...ports("Mic/Line In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
      port("USB (Audio/Control)", "usb", "bidirectional"),
      port("Network", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ── Blaze Audio — PowerZone Connect amplifiers ───────────────────
  {
    id: "c0a80101-0fac-4000-8000-000000000f03",
    deviceType: "amplifier",
    headerColor: "#006aff",
    label: "Blaze PowerZone Connect 1004",
    manufacturer: "Blaze Audio",
    modelNumber: "PowerZone Connect 1004",
    referenceUrl: "https://www.blaze-audio.com/powerzone-connect",
    searchTerms: ["blaze", "powerzone", "connect", "1004", "amplifier", "4 channel", "dsp amp"],
    powerDrawW: 1100,
    voltage: "230V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 333,
    weightKg: 5.4,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4, "phoenix"),
      port("Network (App/Control)", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0fac-4000-8000-000000000f04",
    deviceType: "amplifier",
    headerColor: "#006aff",
    label: "Blaze PowerZone Connect 504D",
    manufacturer: "Blaze Audio",
    modelNumber: "PowerZone Connect 504D",
    referenceUrl: "https://www.blaze-audio.com/powerzone-connect",
    searchTerms: ["blaze", "powerzone", "connect", "504d", "amplifier", "dante", "dsp amp"],
    powerDrawW: 600,
    voltage: "230V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 333,
    weightKg: 5.0,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
      ...ports("Speaker Out", "speaker-level", "output", 4, "phoenix"),
      port("Network (App/Control)", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ── Just Add Power — AV-over-IP ──────────────────────────────────
  {
    id: "c0a80101-0fac-4000-8000-000000000f05",
    deviceType: "av-over-ip",
    label: "Just Add Power 3G+ Transmitter",
    manufacturer: "Just Add Power",
    modelNumber: "3G+ SX (Tx)",
    referenceUrl: "https://www.justaddpower.com/",
    searchTerms: ["just add power", "jap", "avoip", "av over ip", "transmitter", "encoder", "3g"],
    powerDrawW: 8,
    poeDrawW: 8,
    heightMm: 28,
    widthMm: 140,
    depthMm: 92,
    weightKg: 0.4,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Loop Out", "hdmi", "output"),
      port("Network (PoE)", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("IR", "ir", "bidirectional"),
      port("USB", "usb", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0fac-4000-8000-000000000f06",
    deviceType: "av-over-ip",
    label: "Just Add Power 3G+ Receiver",
    manufacturer: "Just Add Power",
    modelNumber: "3G+ RX",
    referenceUrl: "https://www.justaddpower.com/",
    searchTerms: ["just add power", "jap", "avoip", "av over ip", "receiver", "decoder", "3g"],
    powerDrawW: 8,
    poeDrawW: 8,
    heightMm: 28,
    widthMm: 140,
    depthMm: 92,
    weightKg: 0.4,
    ports: [
      port("Network (PoE)", "ethernet", "bidirectional"),
      port("HDMI Out", "hdmi", "output"),
      port("RS-232", "serial", "bidirectional"),
      port("IR", "ir", "bidirectional"),
      port("USB", "usb", "bidirectional"),
    ],
  },

  // ── Projector (PJLink control) ───────────────────────────────────
  {
    id: "c0a80101-0fac-4000-8000-000000000f07",
    deviceType: "projector",
    label: "Projektor (PJLink)",
    manufacturer: "Generic",
    modelNumber: "PJLink Class 2",
    referenceUrl: "https://pjlink.jbmia.or.jp/english/",
    searchTerms: ["projector", "beamer", "pjlink", "control", "hdbaset", "lan control"],
    powerDrawW: 350,
    voltage: "230V",
    heightMm: 140,
    widthMm: 450,
    depthMm: 360,
    weightKg: 6.0,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("LAN (PJLink)", "ethernet", "bidirectional"),
      port("RS-232 (Control)", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ── IP-Symcon — Gebäudeautomations-Controller ────────────────────
  {
    id: "c0a80101-0fac-4000-8000-000000000f08",
    deviceType: "control-processor",
    label: "IP-Symcon Symbox",
    manufacturer: "Symcon",
    modelNumber: "Symbox",
    referenceUrl: "https://www.symcon.de/de/produkt/symbox/",
    searchTerms: ["ip-symcon", "symcon", "symbox", "automation", "controller", "knx", "dali", "visualisierung"],
    powerDrawW: 15,
    heightMm: 90,
    widthMm: 160,
    depthMm: 63,
    weightKg: 0.6,
    ports: [
      port("LAN 1", "ethernet", "bidirectional"),
      port("LAN 2", "ethernet", "bidirectional"),
      ...ports("USB", "usb", "bidirectional", 4),
      port("KNX", "knx", "bidirectional"),
      port("DALI", "dali", "bidirectional"),
      port("RS-485", "serial", "bidirectional"),
      port("HDMI (lokal)", "hdmi", "output"),
      port("DC Power", "power", "input"),
    ],
  },
];
