import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * Intrusion alarm and surveillance: Ajax Systems and Telenot.
 *
 * Signal types:
 *   - "fibra"    → Ajax Fibra, the wired detector bus (4-core: 2 power + 2 data). Runs as
 *                  a beam or a ring; a hub carries several independent lines.
 *   - "jeweller" → Ajax Jeweller, the radio link between a hub and its wireless devices.
 *                  Modelled as a signal on purpose: which hub a detector is enrolled on is
 *                  real commissioning information, and a plan that cannot show it is
 *                  missing the same thing a missing cable would be.
 *   - "bus-2"    → Telenot BUS-2, the wired detector bus of the complex panels.
 *
 * All three are bus topologies, so their ports default to multi-connect (see
 * MULTI_CONNECT_DEFAULT_SIGNALS in connectorTypes.ts) and many devices share one line.
 * Detector addresses go on the placed device as `busAddress` — free text, because Telenot
 * numbers a BUS-2 line differently from the way Ajax numbers a Fibra line.
 *
 * IP cameras hang on "ethernet" and carry `poeDrawW`; there is deliberately no separate
 * ONVIF/RTSP port, since the cable is Ethernet and doubling it up would inflate every
 * pack list.
 *
 * ── On the specs in this file ────────────────────────────────────────────────────────
 * Model names, bus topology and port *kinds* are the load-bearing part and are what
 * planning depends on. Where a figure was not certain it was left out rather than
 * guessed: battery-powered Ajax devices carry no `powerDrawW`, and physical dimensions
 * appear only where they are known. The Telenot detectors are modelled as line devices
 * without a model number, because the panels and the bus are the well-established part
 * of that range and inventing SKUs would be worse than leaving the field empty. Check
 * panel line counts and detector types against the current datasheet before a quote goes
 * out.
 */
export const templates: DeviceTemplate[] = [
  // ══ Ajax — hubs ═════════════════════════════════════════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000101",
    deviceType: "alarm-panel",
    label: "Ajax Hub 2 Plus",
    shortName: "Hub 2 Plus",
    manufacturer: "Ajax Systems",
    modelNumber: "Hub 2 Plus",
    referenceUrl: "https://ajax.systems/products/hub-2-plus/",
    searchTerms: ["ajax", "hub", "zentrale", "alarm", "jeweller", "wings", "panel", "ema"],
    planSymbol: { shape: "square", glyph: "Z" },
    powerDrawW: 10,
    voltage: "110-240V",
    heightMm: 163,
    widthMm: 163,
    depthMm: 36,
    ports: [
      port("AC In", "power", "input"),
      port("LAN", "ethernet", "bidirectional"),
      // One radio port stands for the whole Jeweller side: every wireless device
      // enrolled on the hub connects here, which is what multi-connect is for.
      port("Jeweller", "jeweller", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000102",
    deviceType: "alarm-panel",
    label: "Ajax Hub 2 (4G)",
    shortName: "Hub 2 4G",
    manufacturer: "Ajax Systems",
    modelNumber: "Hub 2 (4G)",
    referenceUrl: "https://ajax.systems/products/hub-2/",
    searchTerms: ["ajax", "hub", "zentrale", "alarm", "jeweller", "4g", "lte", "panel", "ema"],
    planSymbol: { shape: "square", glyph: "Z" },
    powerDrawW: 10,
    voltage: "110-240V",
    heightMm: 163,
    widthMm: 163,
    depthMm: 36,
    ports: [
      port("AC In", "power", "input"),
      port("LAN", "ethernet", "bidirectional"),
      port("Jeweller", "jeweller", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000103",
    deviceType: "alarm-panel",
    label: "Ajax Hub Hybrid (4G)",
    shortName: "Hub Hybrid",
    manufacturer: "Ajax Systems",
    modelNumber: "Hub Hybrid (4G)",
    referenceUrl: "https://ajax.systems/products/hub-hybrid/",
    searchTerms: ["ajax", "hub", "hybrid", "fibra", "jeweller", "zentrale", "alarm", "panel", "ema"],
    planSymbol: { shape: "square", glyph: "Z" },
    powerDrawW: 12,
    voltage: "110-240V",
    heightMm: 163,
    widthMm: 163,
    depthMm: 36,
    ports: [
      port("AC In", "power", "input"),
      port("LAN", "ethernet", "bidirectional"),
      // The hybrid hub is the one device that speaks both sides.
      port("Fibra Line", "fibra", "bidirectional"),
      port("Jeweller", "jeweller", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000104",
    deviceType: "radio-extender",
    label: "Ajax ReX 2",
    shortName: "ReX 2",
    manufacturer: "Ajax Systems",
    modelNumber: "ReX 2",
    referenceUrl: "https://ajax.systems/products/rex-2/",
    searchTerms: ["ajax", "rex", "repeater", "funk", "reichweite", "range extender", "jeweller"],
    planSymbol: { shape: "diamond", glyph: "RX" },
    powerDrawW: 5,
    voltage: "110-240V",
    ports: [
      port("AC In", "power", "input"),
      port("Jeweller (Hub)", "jeweller", "input"),
      port("Jeweller (Devices)", "jeweller", "output"),
    ],
  },

  // ══ Ajax — Jeweller detectors (wireless, battery) ═══════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000110",
    deviceType: "motion-detector",
    label: "Ajax MotionProtect",
    shortName: "MotionProtect",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionProtect",
    referenceUrl: "https://ajax.systems/products/motionprotect/",
    searchTerms: ["ajax", "bewegungsmelder", "pir", "motion", "melder", "jeweller", "funk"],
    // 12 m / 88.5° per datasheet — the figure a coverage area on the plan starts from.
    planSymbol: { shape: "triangle", glyph: "BM" },
    installNotes: "Reichweite 12 m / 88,5°; Montagehöhe 2,4 m",
    heightMm: 110,
    widthMm: 65,
    depthMm: 50,
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000111",
    deviceType: "motion-detector",
    label: "Ajax MotionProtect Curtain",
    shortName: "MotionProtect Curtain",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionProtect Curtain",
    referenceUrl: "https://ajax.systems/products/motionprotect-curtain/",
    searchTerms: ["ajax", "vorhang", "curtain", "bewegungsmelder", "pir", "jeweller", "funk"],
    planSymbol: { shape: "triangle", glyph: "VM" },
    installNotes: "Vorhanglinse, Reichweite 15 m / 6°",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000112",
    deviceType: "motion-detector",
    label: "Ajax MotionCam",
    shortName: "MotionCam",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionCam",
    referenceUrl: "https://ajax.systems/products/motioncam/",
    searchTerms: ["ajax", "motioncam", "bewegungsmelder", "fotoverifikation", "pir", "jeweller", "kamera"],
    planSymbol: { shape: "triangle", glyph: "MC" },
    installNotes: "Bewegungsmelder mit Fotoverifikation; Reichweite 12 m / 88,5°",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000113",
    deviceType: "motion-detector",
    label: "Ajax MotionProtect Outdoor",
    shortName: "MotionProtect Outdoor",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionProtect Outdoor",
    referenceUrl: "https://ajax.systems/products/motionprotect-outdoor/",
    searchTerms: ["ajax", "aussen", "outdoor", "bewegungsmelder", "pir", "jeweller", "funk"],
    planSymbol: { shape: "triangle", glyph: "BA" },
    installNotes: "Außenbereich, zwei PIR-Sensoren; Reichweite 15 m / 60°",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000114",
    deviceType: "opening-detector",
    label: "Ajax DoorProtect",
    shortName: "DoorProtect",
    manufacturer: "Ajax Systems",
    modelNumber: "DoorProtect",
    referenceUrl: "https://ajax.systems/products/doorprotect/",
    searchTerms: ["ajax", "oeffnungsmelder", "magnetkontakt", "tuer", "fenster", "reed", "jeweller"],
    planSymbol: { shape: "circle", glyph: "ÖM" },
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000115",
    deviceType: "opening-detector",
    label: "Ajax DoorProtect Plus",
    shortName: "DoorProtect Plus",
    manufacturer: "Ajax Systems",
    modelNumber: "DoorProtect Plus",
    referenceUrl: "https://ajax.systems/products/doorprotect-plus/",
    searchTerms: ["ajax", "oeffnungsmelder", "erschuetterung", "neigung", "magnetkontakt", "jeweller"],
    planSymbol: { shape: "circle", glyph: "ÖM" },
    installNotes: "Öffnungsmelder mit Erschütterungs- und Neigungssensor",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000116",
    deviceType: "glass-break-detector",
    label: "Ajax GlassProtect",
    shortName: "GlassProtect",
    manufacturer: "Ajax Systems",
    modelNumber: "GlassProtect",
    referenceUrl: "https://ajax.systems/products/glassprotect/",
    searchTerms: ["ajax", "glasbruch", "glass break", "melder", "jeweller", "funk"],
    planSymbol: { shape: "circle", glyph: "GB" },
    installNotes: "Glasbruchmelder, Erfassung bis 9 m",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000117",
    deviceType: "glass-break-detector",
    label: "Ajax CombiProtect",
    shortName: "CombiProtect",
    manufacturer: "Ajax Systems",
    modelNumber: "CombiProtect",
    referenceUrl: "https://ajax.systems/products/combiprotect/",
    searchTerms: ["ajax", "kombimelder", "bewegung", "glasbruch", "combi", "jeweller"],
    planSymbol: { shape: "triangle", glyph: "KM" },
    installNotes: "Bewegung 12 m / 88,5° und Glasbruch bis 9 m in einem Melder",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000118",
    deviceType: "smoke-detector",
    label: "Ajax FireProtect 2",
    shortName: "FireProtect 2",
    manufacturer: "Ajax Systems",
    modelNumber: "FireProtect 2",
    referenceUrl: "https://ajax.systems/products/fireprotect-2/",
    searchTerms: ["ajax", "rauchmelder", "brandmelder", "smoke", "fire", "co", "jeweller"],
    planSymbol: { shape: "circle", glyph: "RM" },
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000119",
    deviceType: "water-leak-detector",
    label: "Ajax LeaksProtect",
    shortName: "LeaksProtect",
    manufacturer: "Ajax Systems",
    modelNumber: "LeaksProtect",
    referenceUrl: "https://ajax.systems/products/leaksprotect/",
    searchTerms: ["ajax", "wassermelder", "leckage", "leak", "wasser", "jeweller"],
    planSymbol: { shape: "circle", glyph: "WM" },
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },

  // ══ Ajax — sirens, keypads, wired bridges ═══════════════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000120",
    deviceType: "siren-indoor",
    label: "Ajax HomeSiren",
    shortName: "HomeSiren",
    manufacturer: "Ajax Systems",
    modelNumber: "HomeSiren",
    referenceUrl: "https://ajax.systems/products/homesiren/",
    searchTerms: ["ajax", "sirene", "innensirene", "signalgeber", "siren", "jeweller"],
    planSymbol: { shape: "diamond", glyph: "SI" },
    installNotes: "Innensirene, 85 dB",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000121",
    deviceType: "siren-outdoor",
    label: "Ajax StreetSiren",
    shortName: "StreetSiren",
    manufacturer: "Ajax Systems",
    modelNumber: "StreetSiren",
    referenceUrl: "https://ajax.systems/products/streetsiren/",
    searchTerms: ["ajax", "sirene", "aussensirene", "signalgeber", "siren", "jeweller"],
    planSymbol: { shape: "diamond", glyph: "AS" },
    installNotes: "Außensirene, 113 dB",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000122",
    deviceType: "siren-outdoor",
    label: "Ajax StreetSiren DoubleDeck",
    shortName: "StreetSiren DoubleDeck",
    manufacturer: "Ajax Systems",
    modelNumber: "StreetSiren DoubleDeck",
    referenceUrl: "https://ajax.systems/products/streetsiren-doubledeck/",
    searchTerms: ["ajax", "sirene", "aussensirene", "doubledeck", "blende", "siren", "jeweller"],
    planSymbol: { shape: "diamond", glyph: "AS" },
    installNotes: "Außensirene mit auswechselbarer Frontblende, 113 dB",
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000123",
    deviceType: "alarm-keypad",
    label: "Ajax KeyPad",
    shortName: "KeyPad",
    manufacturer: "Ajax Systems",
    modelNumber: "KeyPad",
    referenceUrl: "https://ajax.systems/products/keypad/",
    searchTerms: ["ajax", "bedienteil", "tastatur", "keypad", "scharfschalten", "jeweller"],
    planSymbol: { shape: "square", glyph: "BT" },
    heightMm: 150,
    widthMm: 103,
    depthMm: 14,
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000124",
    deviceType: "alarm-keypad",
    label: "Ajax KeyPad TouchScreen",
    shortName: "KeyPad TouchScreen",
    manufacturer: "Ajax Systems",
    modelNumber: "KeyPad TouchScreen",
    referenceUrl: "https://ajax.systems/products/keypad-touchscreen/",
    searchTerms: ["ajax", "bedienteil", "touch", "display", "keypad", "scharfschalten", "jeweller"],
    planSymbol: { shape: "square", glyph: "BT" },
    ports: [port("Jeweller", "jeweller", "bidirectional")],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000125",
    deviceType: "alarm-expander",
    label: "Ajax MultiTransmitter",
    shortName: "MultiTransmitter",
    manufacturer: "Ajax Systems",
    modelNumber: "MultiTransmitter",
    referenceUrl: "https://ajax.systems/products/multitransmitter/",
    searchTerms: ["ajax", "transmitter", "modul", "fremdmelder", "zonen", "integration", "jeweller"],
    planSymbol: { shape: "square", glyph: "MT" },
    voltage: "12V DC",
    ports: [
      port("12V DC In", "power", "input"),
      port("Jeweller", "jeweller", "output"),
      // 18 zones for third-party wired detectors — the reason this module exists.
      ...ports("Zone", "contact-closure", "input", 18),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000126",
    deviceType: "alarm-expander",
    label: "Ajax Transmitter",
    shortName: "Transmitter",
    manufacturer: "Ajax Systems",
    modelNumber: "Transmitter",
    referenceUrl: "https://ajax.systems/products/transmitter/",
    searchTerms: ["ajax", "transmitter", "modul", "fremdmelder", "integration", "jeweller"],
    planSymbol: { shape: "square", glyph: "TR" },
    ports: [
      port("Zone", "contact-closure", "input"),
      port("Jeweller", "jeweller", "output"),
    ],
  },

  // ══ Ajax — Fibra (wired bus) ════════════════════════════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000130",
    deviceType: "motion-detector",
    label: "Ajax MotionProtect Fibra",
    shortName: "MotionProtect Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionProtect Fibra",
    referenceUrl: "https://ajax.systems/products/motionprotect-fibra/",
    searchTerms: ["ajax", "fibra", "bewegungsmelder", "pir", "verdrahtet", "bus", "melder"],
    planSymbol: { shape: "triangle", glyph: "BM" },
    installNotes: "Reichweite 12 m / 88,5°; Speisung über die Fibra-Linie",
    // Bus-powered: the "In" / "Out" pair is what makes a line run through the device,
    // so a Fibra beam can be drawn hop by hop the way it is actually pulled.
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000131",
    deviceType: "motion-detector",
    label: "Ajax MotionCam Fibra",
    shortName: "MotionCam Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "MotionCam Fibra",
    referenceUrl: "https://ajax.systems/products/motioncam-fibra/",
    searchTerms: ["ajax", "fibra", "motioncam", "fotoverifikation", "bewegungsmelder", "bus"],
    planSymbol: { shape: "triangle", glyph: "MC" },
    installNotes: "Bewegungsmelder mit Fotoverifikation; Speisung über die Fibra-Linie",
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000132",
    deviceType: "opening-detector",
    label: "Ajax DoorProtect Fibra",
    shortName: "DoorProtect Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "DoorProtect Fibra",
    referenceUrl: "https://ajax.systems/products/doorprotect-fibra/",
    searchTerms: ["ajax", "fibra", "oeffnungsmelder", "magnetkontakt", "tuer", "fenster", "bus"],
    planSymbol: { shape: "circle", glyph: "ÖM" },
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000133",
    deviceType: "glass-break-detector",
    label: "Ajax GlassProtect Fibra",
    shortName: "GlassProtect Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "GlassProtect Fibra",
    referenceUrl: "https://ajax.systems/products/glassprotect-fibra/",
    searchTerms: ["ajax", "fibra", "glasbruch", "glass break", "melder", "bus"],
    planSymbol: { shape: "circle", glyph: "GB" },
    installNotes: "Glasbruchmelder, Erfassung bis 9 m; Speisung über die Fibra-Linie",
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000134",
    deviceType: "alarm-keypad",
    label: "Ajax KeyPad Fibra",
    shortName: "KeyPad Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "KeyPad Fibra",
    referenceUrl: "https://ajax.systems/products/keypad-fibra/",
    searchTerms: ["ajax", "fibra", "bedienteil", "tastatur", "keypad", "bus"],
    planSymbol: { shape: "square", glyph: "BT" },
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000135",
    deviceType: "siren-outdoor",
    label: "Ajax StreetSiren Fibra",
    shortName: "StreetSiren Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "StreetSiren Fibra",
    referenceUrl: "https://ajax.systems/products/streetsiren-fibra/",
    searchTerms: ["ajax", "fibra", "sirene", "aussensirene", "signalgeber", "bus"],
    planSymbol: { shape: "diamond", glyph: "AS" },
    installNotes: "Außensirene, 113 dB; Speisung über die Fibra-Linie",
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000136",
    deviceType: "siren-indoor",
    label: "Ajax HomeSiren Fibra",
    shortName: "HomeSiren Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "HomeSiren Fibra",
    referenceUrl: "https://ajax.systems/products/homesiren-fibra/",
    searchTerms: ["ajax", "fibra", "sirene", "innensirene", "signalgeber", "bus"],
    planSymbol: { shape: "diamond", glyph: "SI" },
    ports: [
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000137",
    deviceType: "alarm-expander",
    label: "Ajax MultiTransmitter Fibra",
    shortName: "MultiTransmitter Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "MultiTransmitter Fibra",
    referenceUrl: "https://ajax.systems/products/multitransmitter-fibra/",
    searchTerms: ["ajax", "fibra", "transmitter", "fremdmelder", "zonen", "integration", "bus"],
    planSymbol: { shape: "square", glyph: "MT" },
    voltage: "12V DC",
    ports: [
      port("12V DC In", "power", "input"),
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
      ...ports("Zone", "contact-closure", "input", 18),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000138",
    deviceType: "alarm-expander",
    label: "Ajax LineSupply Fibra",
    shortName: "LineSupply Fibra",
    manufacturer: "Ajax Systems",
    modelNumber: "LineSupply Fibra",
    referenceUrl: "https://ajax.systems/products/linesupply-fibra/",
    searchTerms: ["ajax", "fibra", "linesupply", "einspeisung", "netzteil", "bus", "spannung"],
    planSymbol: { shape: "square", glyph: "LS" },
    installNotes: "Speist Spannung in eine lange Fibra-Linie ein",
    voltage: "110-240V",
    ports: [
      port("AC In", "power", "input"),
      port("Fibra In", "fibra", "input"),
      port("Fibra Out", "fibra", "output"),
    ],
  },

  // ══ Ajax — video ════════════════════════════════════════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000140",
    deviceType: "ip-camera",
    label: "Ajax TurretCam (5 MP)",
    shortName: "TurretCam",
    manufacturer: "Ajax Systems",
    modelNumber: "TurretCam 5 MP",
    referenceUrl: "https://ajax.systems/products/turretcam/",
    searchTerms: ["ajax", "kamera", "camera", "turret", "ip", "poe", "onvif", "video", "ueberwachung"],
    // A camera symbol that can be aimed on the plan, with a coverage area to match.
    planSymbol: { shape: "camera", glyph: "K" },
    poeDrawW: 7,
    voltage: "12V DC / PoE",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("12V DC In", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000141",
    deviceType: "ip-camera",
    label: "Ajax BulletCam (5 MP)",
    shortName: "BulletCam",
    manufacturer: "Ajax Systems",
    modelNumber: "BulletCam 5 MP",
    referenceUrl: "https://ajax.systems/products/bulletcam/",
    searchTerms: ["ajax", "kamera", "camera", "bullet", "ip", "poe", "onvif", "video", "ueberwachung"],
    planSymbol: { shape: "camera", glyph: "K" },
    poeDrawW: 7,
    voltage: "12V DC / PoE",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("12V DC In", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000142",
    deviceType: "ip-camera",
    label: "Ajax DomeCam Mini (5 MP)",
    shortName: "DomeCam Mini",
    manufacturer: "Ajax Systems",
    modelNumber: "DomeCam Mini 5 MP",
    referenceUrl: "https://ajax.systems/products/domecam-mini/",
    searchTerms: ["ajax", "kamera", "camera", "dome", "ip", "poe", "onvif", "video", "ueberwachung"],
    planSymbol: { shape: "camera", glyph: "K" },
    poeDrawW: 7,
    voltage: "12V DC / PoE",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("12V DC In", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000143",
    deviceType: "nvr",
    label: "Ajax NVR (16 ch)",
    shortName: "Ajax NVR 16",
    manufacturer: "Ajax Systems",
    modelNumber: "NVR (16-ch)",
    referenceUrl: "https://ajax.systems/products/nvr/",
    searchTerms: ["ajax", "nvr", "recorder", "aufzeichnung", "video", "hdd", "ueberwachung"],
    planSymbol: { shape: "rack", glyph: "NVR" },
    // No PoE ports on the Ajax NVR — the cameras are fed from a separate PoE switch, and
    // stating a budget here would let a plan under-size that switch.
    powerDrawW: 12,
    voltage: "110-240V",
    ports: [
      port("AC In", "power", "input"),
      port("LAN", "ethernet", "bidirectional"),
    ],
  },

  // ══ Telenot — complex panels and BUS-2 ══════════════════════════
  {
    id: "c0a80101-0ba2-4000-8000-000000000150",
    deviceType: "alarm-panel",
    label: "Telenot complex 400H",
    shortName: "complex 400H",
    manufacturer: "Telenot",
    modelNumber: "complex 400H",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "complex", "400h", "zentrale", "emz", "einbruchmeldezentrale", "bus-2", "vds"],
    planSymbol: { shape: "square", glyph: "Z" },
    powerDrawW: 30,
    voltage: "230V",
    ports: [
      port("AC In", "power", "input"),
      ...ports("BUS-2 Line", "bus-2", "bidirectional", 4),
      // Onboard hardwired zones, alongside the bus lines.
      ...ports("Meldergruppe", "contact-closure", "input", 10),
      port("Relais", "contact-closure", "output"),
      port("Übertragungsgerät", "serial", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000151",
    deviceType: "alarm-panel",
    label: "Telenot complex 200H",
    shortName: "complex 200H",
    manufacturer: "Telenot",
    modelNumber: "complex 200H",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "complex", "200h", "zentrale", "emz", "einbruchmeldezentrale", "bus-2", "vds"],
    planSymbol: { shape: "square", glyph: "Z" },
    powerDrawW: 25,
    voltage: "230V",
    ports: [
      port("AC In", "power", "input"),
      ...ports("BUS-2 Line", "bus-2", "bidirectional", 2),
      ...ports("Meldergruppe", "contact-closure", "input", 8),
      port("Relais", "contact-closure", "output"),
      port("Übertragungsgerät", "serial", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000152",
    deviceType: "alarm-transmitter",
    label: "Telenot comXline 3516-2",
    shortName: "comXline 3516",
    manufacturer: "Telenot",
    modelNumber: "comXline 3516-2",
    referenceUrl: "https://www.telenot.com/de/produkte/uebertragungstechnik",
    searchTerms: ["telenot", "comxline", "uebertragungsgeraet", "wählgerät", "ip", "gsm", "lte", "aufschaltung"],
    planSymbol: { shape: "square", glyph: "ÜG" },
    powerDrawW: 6,
    voltage: "12V DC",
    ports: [
      port("12V DC In", "power", "input"),
      port("Zentrale", "serial", "bidirectional"),
      port("LAN", "ethernet", "bidirectional"),
      port("Antenne", "rf", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000153",
    deviceType: "alarm-keypad",
    label: "Telenot Bedienteil BT 820",
    shortName: "BT 820",
    manufacturer: "Telenot",
    modelNumber: "BT 820",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bedienteil", "bt 820", "tastatur", "scharfschalten", "bus-2"],
    planSymbol: { shape: "square", glyph: "BT" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000154",
    deviceType: "transponder-reader",
    label: "Telenot comlock 380",
    shortName: "comlock 380",
    manufacturer: "Telenot",
    modelNumber: "comlock 380",
    referenceUrl: "https://www.telenot.com/de/produkte/zutrittskontrolle",
    searchTerms: ["telenot", "comlock", "leser", "transponder", "zutritt", "scharfschalten", "bus-2"],
    planSymbol: { shape: "square", glyph: "TL" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },

  // ── Telenot BUS-2 line devices ──────────────────────────────────
  // Deliberately without a model number: the panels, the bus and the wiring are the
  // established part of this range, and picking SKUs for the detectors would be a guess
  // dressed up as data. Set the model on the placed device once the datasheet is at hand.
  {
    id: "c0a80101-0ba2-4000-8000-000000000160",
    deviceType: "motion-detector",
    label: "Telenot BUS-2 Bewegungsmelder",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "bewegungsmelder", "pir", "melder", "infrarot"],
    planSymbol: { shape: "triangle", glyph: "BM" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000161",
    deviceType: "opening-detector",
    label: "Telenot BUS-2 Öffnungsmelder",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "oeffnungsmelder", "magnetkontakt", "tuer", "fenster", "reed"],
    planSymbol: { shape: "circle", glyph: "ÖM" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000162",
    deviceType: "glass-break-detector",
    label: "Telenot BUS-2 Glasbruchmelder",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "glasbruch", "melder", "glass break"],
    planSymbol: { shape: "circle", glyph: "GB" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000163",
    deviceType: "siren-outdoor",
    label: "Telenot Außensignalgeber (BUS-2)",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "sirene", "aussensignalgeber", "signalgeber", "blitzleuchte"],
    planSymbol: { shape: "diamond", glyph: "AS" },
    installNotes: "Außensignalgeber mit Blitzleuchte",
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000164",
    deviceType: "siren-indoor",
    label: "Telenot Innensignalgeber (BUS-2)",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "sirene", "innensignalgeber", "signalgeber"],
    planSymbol: { shape: "diamond", glyph: "SI" },
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
    ],
  },
  {
    id: "c0a80101-0ba2-4000-8000-000000000165",
    deviceType: "alarm-expander",
    label: "Telenot BUS-2 Melderabschlussmodul",
    manufacturer: "Telenot",
    referenceUrl: "https://www.telenot.com/de/produkte/einbruchmeldetechnik",
    searchTerms: ["telenot", "bus-2", "modul", "erweiterung", "meldergruppe", "abschluss", "fremdmelder"],
    planSymbol: { shape: "square", glyph: "EM" },
    installNotes: "Bindet konventionelle Meldergruppen an die BUS-2-Linie an",
    ports: [
      port("BUS-2 In", "bus-2", "input"),
      port("BUS-2 Out", "bus-2", "output"),
      ...ports("Meldergruppe", "contact-closure", "input", 4),
    ],
  },
];
