/**
 * Turn the BHE "Symbole CD" into the plan symbol library.
 *
 * The CD ships every symbol five times over — bmp, dwg, dxf, pdf, tif. The PDF is the only
 * one that is both vector and readable without a CAD library, so that is the source: each
 * one becomes a cropped SVG under public/symbols/bhe/, and the index of what exists becomes
 * src/symbolLibraryCatalog.ts.
 *
 * Run it with the CD reachable:
 *   node tools/bheSymbols.mjs "<path to Symbole CD>"
 *
 * The drawings themselves are BHE member material. They are generated, not committed —
 * see public/symbols/bhe/README.md for how they reach the server.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_SRC = "/Users/jean-luc/Library/CloudStorage/OneDrive-FACEGmbH/2 FACE Share Ordner/1 Lieferanten + Verträge/BHE/Symbole CD";
const SRC = process.argv[2] || DEFAULT_SRC;
const OUT_DIR = join(ROOT, "public", "symbols", "bhe");
const CATALOG = join(ROOT, "src", "symbolLibraryCatalog.ts");

/** "9.1_Kameras" → { no: "9.1", label: "Kameras" }; "1_Einbruchmeldetechnik" → { no: "1", … } */
function splitNumbered(name) {
  const m = /^(\d+(?:\.\d+)?)[_ ]+(.*)$/.exec(name);
  return m ? { no: m[1], label: m[2].replace(/_/g, " ").trim() } : { no: "", label: name.replace(/_/g, " ").trim() };
}

function slug(s) {
  return s
    .toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Poppler writes a standalone document; the library only needs the drawing. */
function tightenSvg(svg) {
  return svg
    .replace(/<\?xml[^>]*\?>\s*/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s*\n\s*/g, "\n")
    .trim();
}

function walk(dir, trail = []) {
  const out = [];
  for (const entry of readdirSync(dir).sort()) {
    if (entry.startsWith(".")) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, [...trail, entry]));
    else if (entry.toLowerCase().endsWith(".pdf") && trail.length > 0) out.push({ full, trail, file: entry });
  }
  return out;
}

const pdfs = walk(SRC);
if (pdfs.length === 0) {
  console.error(`No symbol PDFs under ${SRC}`);
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const groups = new Map(); // category id → { id, no, label, parentLabel, symbols: [] }
let bytes = 0;

for (const { full, trail, file } of pdfs) {
  const top = splitNumbered(trail[0]);
  const sub = trail.length > 1 ? splitNumbered(trail[trail.length - 1]) : null;
  const catNo = sub?.no || top.no;
  const catId = slug(`${catNo}-${sub ? sub.label : top.label}`);
  const name = basename(file, ".pdf").replace(/_/g, " ").trim();
  const id = `${catId}/${slug(name)}`;
  const outFile = join(OUT_DIR, `${id}.svg`);

  mkdirSync(dirname(outFile), { recursive: true });
  execFileSync("pdftocairo", ["-svg", full, outFile]);
  const svg = tightenSvg(readFileSync(outFile, "utf8"));
  writeFileSync(outFile, svg);
  bytes += Buffer.byteLength(svg);

  if (!groups.has(catId)) {
    groups.set(catId, { id: catId, no: catNo, label: sub ? sub.label : top.label, section: top.label, symbols: [] });
  }
  groups.get(catId).symbols.push({ id, name });
}

const cats = [...groups.values()].sort((a, b) =>
  a.no.localeCompare(b.no, "de", { numeric: true }) || a.label.localeCompare(b.label, "de"));

const header = `/**
 * The BHE symbol library — what is on the "Symbole CD", as the app sees it.
 *
 * Generated by tools/bheSymbols.mjs; do not edit by hand. The drawings themselves live
 * under public/symbols/bhe/ and are fetched by id, so a plan file carries the id rather
 * than the artwork.
 */
import type { SymbolLibraryCategory } from "./symbolLibrary";

export const BHE_CATEGORIES: SymbolLibraryCategory[] = ${JSON.stringify(cats, null, 2)};
`;
writeFileSync(CATALOG, header);

console.log(`${pdfs.length} symbols in ${cats.length} categories, ${(bytes / 1024).toFixed(0)} KB of SVG`);
console.log(`  → ${relative(ROOT, OUT_DIR)}`);
console.log(`  → ${relative(ROOT, CATALOG)}`);
