/**
 * The BHE symbol library index — generated by tools/bheSymbols.mjs, do not edit by hand.
 *
 * Empty here: the artwork is member material and is not committed. Run the generator with
 * the "Symbole CD" reachable and this file, plus public/symbols/bhe/, fill in.
 */
import type { SymbolLibraryCategory } from "./symbolLibrary";

export const BHE_CATEGORIES: SymbolLibraryCategory[] = [];
