/**
 * The BHE symbol library — the drawn symbols of German security engineering.
 *
 * The BHE (Bundesverband Sicherheitstechnik) publishes one symbol per component, and plans
 * handed to an installer, an insurer or a Sachverständiger are read against them. Drawing a
 * camera as a triangle is fine for a workshop sketch and wrong for a Anlagenbeschreibung.
 *
 * What ships is the index, not the artwork: every symbol is an SVG under public/symbols/bhe/
 * fetched by id, so a plan file carries the id — nothing about the drawing itself travels
 * through a project file, and re-drawn artwork reaches old plans.
 *
 * The catalogue is generated by tools/bheSymbols.mjs from the member CD. Where it is not
 * installed the library is simply empty, every lookup here answers "nothing", and the app
 * draws the shapes it always drew.
 */
import { BHE_CATEGORIES } from "./symbolLibraryCatalog";

export interface SymbolLibrarySymbol {
  /** "<category>/<name>", e.g. "9-1-kameras/fix-dome". Stable: it is what a plan stores. */
  id: string;
  /** As the CD names it, e.g. "Schwenk-Neige Kamera". */
  name: string;
}

export interface SymbolLibraryCategory {
  id: string;
  /** BHE's own numbering, e.g. "9.1" — the order plans and the prospectus are in. */
  no: string;
  label: string;
  /** The top-level chapter, e.g. "Video-Überwachungstechnik". */
  section: string;
  symbols: SymbolLibrarySymbol[];
}

export interface SymbolLibraryHit {
  id: string;
  name: string;
  category: SymbolLibraryCategory;
}

/** Where the artwork is served from. Same origin, so a canvas drawn from it stays clean
 *  and the PDF export can rasterize it. */
export const SYMBOL_LIBRARY_BASE = "/symbols/bhe/";

export function symbolLibraryCategories(): SymbolLibraryCategory[] {
  return BHE_CATEGORIES;
}

/** Is the artwork installed on this build? Empty means the CD was never converted. */
export function symbolLibraryInstalled(categories: SymbolLibraryCategory[] = BHE_CATEGORIES): boolean {
  return categories.length > 0;
}

export function symbolLibraryUrl(id: string): string {
  return `${SYMBOL_LIBRARY_BASE}${id}.svg`;
}

export function findSymbolLibraryEntry(
  id: string | undefined,
  categories: SymbolLibraryCategory[] = BHE_CATEGORIES,
): SymbolLibraryHit | undefined {
  if (!id) return undefined;
  for (const category of categories) {
    const symbol = category.symbols.find((s) => s.id === id);
    if (symbol) return { id: symbol.id, name: symbol.name, category };
  }
  return undefined;
}

/** What to call a symbol in the UI. A plan drawn on a build with the library open on one
 *  without it still says something sensible rather than showing a raw id. */
export function symbolLibraryName(
  id: string | undefined,
  categories: SymbolLibraryCategory[] = BHE_CATEGORIES,
): string {
  if (!id) return "";
  const hit = findSymbolLibraryEntry(id, categories);
  if (hit) return hit.name;
  const tail = id.split("/").pop() ?? id;
  return tail.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase());
}

/** Free-text search over name and category. Matches at the start of a word rank first —
 *  typing "dome" should offer Fix-Dome before "Vandalismusgeschützte Domekuppel". */
export function searchSymbolLibrary(
  query: string,
  categories: SymbolLibraryCategory[] = BHE_CATEGORIES,
  limit = 80,
): SymbolLibraryHit[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const hits: { hit: SymbolLibraryHit; score: number }[] = [];
  for (const category of categories) {
    const inCategory = `${category.no} ${category.label} ${category.section}`.toLowerCase().includes(q);
    for (const symbol of category.symbols) {
      const name = symbol.name.toLowerCase();
      let score = -1;
      if (name.startsWith(q)) score = 3;
      else if (new RegExp(`\\b${escapeRegExp(q)}`).test(name)) score = 2;
      else if (name.includes(q)) score = 1;
      else if (inCategory) score = 0;
      if (score >= 0) hits.push({ hit: { id: symbol.id, name: symbol.name, category }, score });
    }
  }
  return hits
    .sort((a, b) => b.score - a.score || a.hit.name.localeCompare(b.hit.name, "de"))
    .slice(0, limit)
    .map((h) => h.hit);
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Which BHE symbol a device type asks for.
 *
 * The rules are written against the CD's numbering and its German names rather than against
 * exact ids: the chapter a symbol lives in is fixed by the BHE, the file name is not, and a
 * rule that finds nothing simply yields nothing — the device then keeps the drawn shape it
 * has always had. That is why every rule may list several names, narrowest first.
 */
interface AssignmentRule {
  /** Matched against the device type, lower-cased. */
  device: RegExp;
  /** Matched against the category number ("9.1") — the BHE chapter. */
  chapter: RegExp;
  /** Candidate names inside that chapter, best first. */
  names: RegExp[];
}

const ASSIGNMENT_RULES: AssignmentRule[] = [
  // ── 9 Video-Überwachungstechnik ──
  { device: /ptz|speed.?dome|schwenk/, chapter: /^9(\.1)?$/, names: [/speed.?dome/, /schwenk/, /kamera/] },
  { device: /thermal|thermo|waerme|wärme/, chapter: /^9(\.1)?$/, names: [/thermal|thermo/, /kamera/] },
  { device: /dome/, chapter: /^9(\.1)?$/, names: [/fix.?dome/, /dome/, /kamera/] },
  { device: /bullet|tube/, chapter: /^9(\.1)?$/, names: [/bullet/, /kamera/] },
  { device: /camera|kamera/, chapter: /^9(\.1)?$/, names: [/fix.?dome/, /boxkamera/, /kamera/] },
  { device: /nvr|dvr|recorder|rekorder/, chapter: /^9(\.5)?$/, names: [/rekorder|recorder|aufzeichnung/, /zentrale/] },
  { device: /monitor|display|screen/, chapter: /^9(\.5)?$/, names: [/monitor/, /bildschirm/] },

  // ── 1 Einbruchmeldetechnik ──
  { device: /motion|pir|bewegung/, chapter: /^1$/, names: [/passiv.?infrarot|bewegungsmelder/, /melder/] },
  { device: /glass|glasbruch/, chapter: /^1$/, names: [/glasbruch/] },
  { device: /door.?contact|magnet|reed|oeffnung|öffnung/, chapter: /^1$/, names: [/magnetkontakt|öffnungsmelder|oeffnungsmelder/, /kontakt/] },
  { device: /alarm.?panel|intrusion|einbruchmelderzentrale|emz/, chapter: /^7$/, names: [/einbruchmelderzentrale|zentrale/] },

  // ── 4 Signalgeber ──
  { device: /siren|sounder|sirene|horn|blitz/, chapter: /^4$/, names: [/sirene/, /blitzleuchte/, /signalgeber/] },

  // ── 5 Brandmeldetechnik ──
  { device: /smoke|rauchmelder/, chapter: /^5$/, names: [/rauchmelder/, /melder/] },
  { device: /heat.?detector|waermemelder|wärmemelder/, chapter: /^5$/, names: [/wärmemelder|waermemelder/, /melder/] },
  { device: /fire.?panel|bma|brandmelderzentrale/, chapter: /^5$/, names: [/brandmelderzentrale|zentrale/] },

  // ── 10 Zutrittssteuerung ──
  { device: /card.?reader|kartenleser|zutritt|access.?control/, chapter: /^10$/, names: [/leser/, /ausweis/] },
  { device: /fingerprint|biometric/, chapter: /^10$/, names: [/fingerprint/, /biometrisch/] },

  // ── 6 Schalteinrichtungen ──
  { device: /keypad|bedienteil|blockschloss/, chapter: /^6$/, names: [/bedienteil|blockschloss/, /schalteinrichtung/] },
];

export function defaultSymbolLibraryIdFor(
  deviceType: string | undefined,
  categories: SymbolLibraryCategory[] = BHE_CATEGORIES,
): string | undefined {
  const type = (deviceType ?? "").toLowerCase();
  if (!type) return undefined;
  for (const rule of ASSIGNMENT_RULES) {
    if (!rule.device.test(type)) continue;
    const chapters = categories.filter((c) => rule.chapter.test(c.no));
    for (const name of rule.names) {
      for (const category of chapters) {
        const symbol = category.symbols.find((s) => name.test(s.name.toLowerCase()));
        if (symbol) return symbol.id;
      }
    }
  }
  return undefined;
}
